### ISSUE TITLE
About Travis CI

### ISSUE THREAD

**Issue by dok42** [dok42/Hack-dok42#2]
While looking at Readme.md, I did notice this thing called Travis CI.
What is it and, do I need it to be in this "my" derivate version of the Readme ? 

@chrissimpkins

**Comment by chrissimpkins** [comment]
Travis CI is a continuous integration testing service.  We use it to test the typeface source and shell scripts with each new commit that is pushed to the repository.  You can sign up for an account and begin testing this repository in the same fashion using the upstream Hack tests that are scripted in the .travis.yml file.

The link to the Travis site is https://travis-ci.org/ .  Once you signup for an account using your Github account and provide Travis with permissions, you can import and activate any of your github.com/dok42 repositories for Travis testing.  Many more details in their documentation.

**Comment by dok42** [comment]
Ok, I've done it. Signed up.
Do you have any advice for settings ?
Also, there are actually 4 build job, should I keep all of them? If I understood right, it's 2 for a testing Linux env, and 2 for OS X env.

First build took 20 minutes total.

**Comment by chrissimpkins** [comment]
Yes there are individual platform specific builds for linting the shell scripts and individual platform specific builds of the fonts from source (including source builds of dependencies for the builds).  The OS X builds take forever because they always get queued.   The Linux builds should take about four to five mins.  Up to you if you want to keep the OS X builds.  I like to make sure that we don't do anything that prevents users on both platforms from building the fonts when we make new commits to the repository.   You can modify the platform build types in the `.travis.yml` settings file.
